spring.application.name=vendeFacil
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:cardapiofacildb
spring.jpa.hibernate.ddl-auto=update
# Inclui a mensagem do erro no corpo da resposta (ajuda a visualizar 404/400 no Postman)
server.error.include-message=always
# Não expõe o stacktrace no corpo da resposta (resposta de erro mais limpa)
server.error.include-stacktrace=never
